version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.4-stretch-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_DB: estimation_of_tasks_test

    working_directory: ~/repo

    steps:
      - checkout

      - run: gem install bundler -v 2.0.1

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vender/bundle
